import Head from "next/head";
import Jumbotron from "../components/Jumbotron/Jumbotron.js";
import Nav from "../components/Nav/Nav.js";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tickle me whiskers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Nav />
        <Jumbotron />
      </div>
    </div>
  );
}
